### ISSUE TITLE
1005 行 错误

### ISSUE THREAD

**Issue by iamapig120** [Fr0stbyteR/Majsoul-Helper#1]
```iew.DesktopMgr.Inst.mainrole.during_liqi = true;```
view 少了个 v……
此外似乎牌山没用上……目前会出现自动立直听0张的情况

**Comment by Fr0stbyteR** [comment]
> `iew.DesktopMgr.Inst.mainrole.during_liqi = true;`
> view 少了个 v……
> 此外似乎牌山没用上……目前会出现自动立直听0张的情况

已修正
暂时还是无视牌山的啦
