### ISSUE TITLE
你好，我想可否做一个仅提示摸切的脚本

### ISSUE THREAD

**Issue by liuyuanhao** [Fr0stbyteR/Majsoul-Helper#17]
不需要牌校计算，只显示牌河里的摸切

**Comment by Fr0stbyteR** [comment]
> 不需要牌校计算，只显示牌河里的摸切

刚空下来，准备做了

**Comment by liuyuanhao** [comment]
好的~谢谢

**Comment by xlnx** [comment]
只摸切的话，考虑删掉这个if。
https://github.com/Fr0stbyteR/Majsoul-Helper/blob/0ebfeda32bedbad6f65b45deaa6c203df76ea967/main.js#L956

**Comment by liuyuanhao** [comment]
好像不行。。我删了之后整个就没效果了。我想是只保留牌河里手切和摸切的明暗变化来区分手切和摸切- -

**Comment by liuyuanhao** [comment]
可以了。。谢谢，我多删了一个大括号。。

**Comment by Fr0stbyteR** [comment]
> 可以了。。谢谢，我多删了一个大括号。。

新版本里可以选择了
