### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by ayssia** [Fr0stbyteR/Majsoul-Helper#18]
1. 对三人麻将中 1m/9m 的处理，三人麻将中没有 2m~8m 这几张牌。
2. 对他家副露的处理，例如他家碰了东，又切了一张南，此时如果自己手上有一张东和一张南，脚本没有考虑到这一点，东和南的进张数仍然完全相同。

**Comment by Fr0stbyteR** [comment]
> 1. 对三人麻将中 1m/9m 的处理，三人麻将中没有 2m~8m 这几张牌。
> 2. 对他家副露的处理，例如他家碰了东，又切了一张南，此时如果自己手上有一张东和一张南，脚本没有考虑到这一点，东和南的进张数仍然完全相同。

找了一圈没发现怎么判定本局游戏是三麻还是四麻。。谁知道的话请告诉我下。。
理论上副露已经在判定范围之内了。是不是没更新版本？然后我正在优化这个判定，下个版本应该会舒服很多。

**Comment by ayssia** [comment]
尝试找了一下，是
view.DesktopMgr.Inst.player_datas.length
4就是四麻，3就是三麻。

副露的问题是我xjb改改坏了。。我自己又修好了233

**Comment by Fr0stbyteR** [comment]
> 尝试找了一下，是
> view.DesktopMgr.Inst.player_datas.length
> 4就是四麻，3就是三麻。
> 
> 副露的问题是我xjb改改坏了。。我自己又修好了233

弄好了
