### ISSUE TITLE
新版下关于设置按钮的两个问题

### ISSUE THREAD

**Issue by DCxDESIGN** [Fr0stbyteR/Majsoul-Helper#20]
您好，感谢开发，更新新版之后遇到两个有关联的问题：
1. 如果使用浏览器配合油猴插件，右下角的按钮点击后会弹出新标签（傲游5），设置完成后如果关闭标签将不能保存设置内容。
2. 如果使用Majsoul-Plus，因为不支持新开页面，导致点击右下角按钮后不会有反应，也就无法进行设置。

**Comment by Fr0stbyteR** [comment]
1. 暂时没有保存设置的功能。我考虑以后添加。
2. 我本人没有用过 Majsoul-Plus，这个问题可能因为在它的 config.js 里没有为游戏窗口设置 nativeWindowOpen。有空我会尝试一下。

**Comment by DCxDESIGN** [comment]
1. 那么目前使用的话就只能每次重新设置且保持设置标签开启，是这样吧？
2. 好的谢谢

**Comment by Fr0stbyteR** [comment]
您可以在设置完毕后关闭标签，设置将会应用直到游戏主窗口被关闭。

**Comment by DCxDESIGN** [comment]
好的，另外如果游戏主窗口保持开启，设置完成后关闭设置标签，再次打开设置标签时设置内容会重新显示为默认（但游戏主界面依然保留了上一次设置的状态，直到设置内容被再次更改）

**Comment by Fr0stbyteR** [comment]
> 好的，另外如果游戏主窗口保持开启，设置完成后关闭设置标签，再次打开设置标签时设置内容会重新显示为默认（但游戏主界面依然保留了上一次设置的状态，直到设置内容被再次更改）

现在可以保存内容了，
雀魂Plus应该也能使用了，但是千万千万不要关掉辅助界面，会导致游戏主界面黑屏。

**Comment by DCxDESIGN** [comment]
明白，谢谢
