### ISSUE TITLE
新版下关于壁牌显示的问题

### ISSUE THREAD

**Issue by DCxDESIGN** [Fr0stbyteR/Majsoul-Helper#21]
您好，感谢开发，更新新版之后在牌河判断上出现了之前没有的bug:
1. 当手牌点击任何一张牌时，如果牌河里有壁牌且为摸打牌，该牌会被点亮但不会被染色
2. 当手牌点击任何一张牌时，如果牌河里有壁牌且不为摸打牌，该牌不会被染色

**Comment by Fr0stbyteR** [comment]
1. 确实是疏忽了，下个版本会修改。
2. 在这个版本里，只有出现3张以上的壁牌会被染色。

**Comment by DCxDESIGN** [comment]
好的明白，谢谢

**Comment by Fr0stbyteR** [comment]
> 好的明白，谢谢

已修复
