### ISSUE TITLE
关于新版下“防”模式不生效的问题

### ISSUE THREAD

**Issue by DCxDESIGN** [Fr0stbyteR/Majsoul-Helper#23]
您好，感谢开发。
新的这一版试了几局，浏览器+油猴 和 Majsoul-Plus 下也都试了下，“防”模式好像有点问题，全程手牌不会有任何牌被染色，麻烦检查一下

**Comment by Fr0stbyteR** [comment]
> 您好，感谢开发。
> 新的这一版试了几局，浏览器+油猴 和 Majsoul-Plus 下也都试了下，“防”模式好像有点问题，全程手牌不会有任何牌被染色，麻烦检查一下

这功能还没做呢。。只是先把按钮做好了。。

**Comment by DCxDESIGN** [comment]
好……好的…………
但我为什么记得上一版还是上上一版（刚有选项菜单的那版）是有的。。也许是我记错了。。

**Comment by Fr0stbyteR** [comment]
> 好……好的…………
> 但我为什么记得上一版还是上上一版（刚有选项菜单的那版）是有的。。也许是我记错了。。

现在有简单的防守功能了
