### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by purerosefallen** [Fr0stbyteR/Majsoul-Helper#24]
May I ask how to enable the auto-play function? I've seen other issues discussing on this mechanic, but none of the documents showed anything about this.

**Comment by Fr0stbyteR** [comment]
> May I ask how to enable the auto-play function? I've seen other issues discussing on this mechanic, but none of the documents showed anything about this.

This is because Majsoul officially oppose to the usage of auto-play, and the function is not completely reliable yet. if you would like to try out, you can enable it by executing `helper.auto = true;` in console.

**Comment by purerosefallen** [comment]
How is the risk of leading my Majsoul account being banned?

**Comment by Fr0stbyteR** [comment]
> How is the risk of leading my Majsoul account being banned?
> In addition, are there any hints for suggestions of whether Chow, Peng, Gang or not?

I received one report of ban before adding a random delay on discarding tile. I'm not sure how he got banned. 
For the moment, it's looking for riichi in fastest way, behaves exactly as AI easy in game. So no fuuro.
I'm working on it for defensive aspect. An AI that can do fuuro is demanding a lot of additional analysis, in my opinion.

**Comment by purerosefallen** [comment]
Thanks. At first my idea was, to modify this project for a little, and make it auto-join ranked games earning pts, and place the whole system on a VPS. Perhaps I would gave up this plan..

**Comment by Fr0stbyteR** [comment]
> Thanks. At first my idea was, to modify this project for a little, and make it auto-join ranked games earning pts, and place the whole system on a VPS. Perhaps I would gave up this plan..

FYI, take a look at line 146 and 147, these are for auto end a current game then match a new one.
