### ISSUE TITLE
2019/03/08 0.3.3 更新後插件失效

### ISSUE THREAD

**Issue by NeapolitanIcecream** [Fr0stbyteR/Majsoul-Helper#25]
更新自 Greasyfork，安裝到油猴腳本。2019/03/08 0.3.3 更新後找不到前一個版本所見「雀魂輔助」按鈕，亦沒有牌河和手牌染色、自動和了、段位顯示等。

**Comment by Fr0stbyteR** [comment]
> 更新自 Greasyfork，安裝到油猴腳本。2019/03/08 0.3.3 更新後找不到前一個版本所見「雀魂輔助」按鈕，亦沒有牌河和手牌染色、自動和了、段位顯示等。

我沒能復現您的問題，您可以試試刪除腳本重新安裝，檢查腳本內容是否和 Github 上的一致，如果一致，麻煩按下 F12 將控制台中出現的信息匯報給我。

**Comment by kaguyas** [comment]
Syntax error @ "Majsoul Helper"!
##########################
JSHINT output:
##########################

SyntaxError: Unexpected token =
    at eval (<anonymous>)
    at <anonymous>:2:494
    at Object.b [as F_c] (<anonymous>:1:415)
    at Object.E_u (<anonymous>:3:158)
    at v (eval at exec_fn (:1:108), <anonymous>:64:439)
    at ja (eval at exec_fn (:1:108), <anonymous>:63:194)
    at Object.create (eval at exec_fn (:1:108), <anonymous>:75:51)
    at c (eval at exec_fn (:1:108), <anonymous>:16:273)
(anonymous) @ VM57:64
22:39:56.278 VM57:64 Uncaught SyntaxError: Unexpected token =
    at eval (<anonymous>)
    at <anonymous>:2:494
    at Object.b [as F_c] (<anonymous>:1:415)
    at Object.E_u (<anonymous>:3:158)
    at v (eval at exec_fn (:1:108), <anonymous>:64:439)
    at ja (eval at exec_fn (:1:108), <anonymous>:63:194)
    at Object.create (eval at exec_fn (:1:108), <anonymous>:75:51)
    at c (eval at exec_fn (:1:108), <anonymous>:16:273)

**Comment by NeapolitanIcecream** [comment]
> > 更新自 Greasyfork，安裝到油猴腳本。2019/03/08 0.3.3 更新後找不到前一個版本所見「雀魂輔助」按鈕，亦沒有牌河和手牌染色、自動和了、段位顯示等。
> 
> 我沒能復現您的問題，您可以試試刪除腳本重新安裝，檢查腳本內容是否和 Github 上的一致，如果一致，麻煩按下 F12 將控制台中出現的信息匯報給我。

我嘗試重裝腳本但是沒有變化。
我在另一台電腦的相同環境下沒能復現問題。我認為這是我的瀏覽器配置導致的問題。

**Comment by Fr0stbyteR** [comment]
> > > 更新自 Greasyfork，安裝到油猴腳本。2019/03/08 0.3.3 更新後找不到前一個版本所見「雀魂輔助」按鈕，亦沒有牌河和手牌染色、自動和了、段位顯示等。
> > 
> > 
> > 我沒能復現您的問題，您可以試試刪除腳本重新安裝，檢查腳本內容是否和 Github 上的一致，如果一致，麻煩按下 F12 將控制台中出現的信息匯報給我。
> 
> 我嘗試重裝腳本但是沒有變化。
> 我在另一台電腦的相同環境下沒能復現問題。我認為這是我的瀏覽器配置導致的問題。

能告訴我一下出現問題的瀏覽器和版本么

**Comment by Fr0stbyteR** [comment]
我用 Firefox 复现了这个问题，是由于编译器不支持 class static property，已经修复。请更新版本

> Syntax error @ "Majsoul Helper"!
> ##########################
> JSHINT output:
> ##########################
> 
> SyntaxError: Unexpected token =
> at eval ()
> at :2:494
> at Object.b [as F_c] (:1:415)
> at Object.E_u (:3:158)
> at v (eval at exec_fn (:1:108), :64:439)
> at ja (eval at exec_fn (:1:108), :63:194)
> at Object.create (eval at exec_fn (:1:108), :75:51)
> at c (eval at exec_fn (:1:108), :16:273)
> (anonymous) @ VM57:64
> 22:39:56.278 VM57:64 Uncaught SyntaxError: Unexpected token =
> at eval ()
> at :2:494
> at Object.b [as F_c] (:1:415)
> at Object.E_u (:3:158)
> at v (eval at exec_fn (:1:108), :64:439)
> at ja (eval at exec_fn (:1:108), :63:194)
> at Object.create (eval at exec_fn (:1:108), :75:51)
> at c (eval at exec_fn (:1:108), :16:273)



> > > 更新自 Greasyfork，安裝到油猴腳本。2019/03/08 0.3.3 更新後找不到前一個版本所見「雀魂輔助」按鈕，亦沒有牌河和手牌染色、自動和了、段位顯示等。
> > 
> > 
> > 我沒能復現您的問題，您可以試試刪除腳本重新安裝，檢查腳本內容是否和 Github 上的一致，如果一致，麻煩按下 F12 將控制台中出現的信息匯報給我。
> 
> 我嘗試重裝腳本但是沒有變化。
> 我在另一台電腦的相同環境下沒能復現問題。我認為這是我的瀏覽器配置導致的問題。

**Comment by NeapolitanIcecream** [comment]
> 我用 Firefox 复现了这个问题，是由于编译器不支持 class static property，已经修复。请更新版本
> 
> > Syntax error @ "Majsoul Helper"!
> > ##########################
> > JSHINT output:
> > ##########################
> > SyntaxError: Unexpected token =
> > at eval ()
> > at :2:494
> > at Object.b [as F_c] (:1:415)
> > at Object.E_u (:3:158)
> > at v (eval at exec_fn (:1:108), :64:439)
> > at ja (eval at exec_fn (:1:108), :63:194)
> > at Object.create (eval at exec_fn (:1:108), :75:51)
> > at c (eval at exec_fn (:1:108), :16:273)
> > (anonymous) @ VM57:64
> > 22:39:56.278 VM57:64 Uncaught SyntaxError: Unexpected token =
> > at eval ()
> > at :2:494
> > at Object.b [as F_c] (:1:415)
> > at Object.E_u (:3:158)
> > at v (eval at exec_fn (:1:108), :64:439)
> > at ja (eval at exec_fn (:1:108), :63:194)
> > at Object.create (eval at exec_fn (:1:108), :75:51)
> > at c (eval at exec_fn (:1:108), :16:273)
> 
> > > > 更新自 Greasyfork，安裝到油猴腳本。2019/03/08 0.3.3 更新後找不到前一個版本所見「雀魂輔助」按鈕，亦沒有牌河和手牌染色、自動和了、段位顯示等。
> > > 
> > > 
> > > 我沒能復現您的問題，您可以試試刪除腳本重新安裝，檢查腳本內容是否和 Github 上的一致，如果一致，麻煩按下 F12 將控制台中出現的信息匯報給我。
> > 
> > 
> > 我嘗試重裝腳本但是沒有變化。
> > 我在另一台電腦的相同環境下沒能復現問題。我認為這是我的瀏覽器配置導致的問題。

通過更新，問題已經解決了。感謝您的支持。
我需要為自己武斷地認定不能復現問題道歉，因為我只在相同「插件」環境下進行了測試，但用的瀏覽器是 Chrome 而不是 Firefox。
