### ISSUE TITLE
建议自动打牌加入随机延迟

### ISSUE THREAD

**Issue by luciouskami** [Fr0stbyteR/Majsoul-Helper#3]
0延迟导致封禁，7天（可能是因为我号比较值钱）

**Comment by FlyingBamboo** [comment]
别用自动打牌吧，或者优化一下再用。。没有吃碰，不防即立，能上分吗
另外好像有坐庄的时候不能自动打牌的BUG，因为初始派牌的动画时间太长了

**Comment by Fr0stbyteR** [comment]
> 0延迟导致封禁，7天（可能是因为我号比较值钱）

啊 不好意思导致你封禁了，这个功能确实还有些问题，暂时别使用了

**Comment by luciouskami** [comment]
> > 0延迟导致封禁，7天（可能是因为我号比较值钱）
> 
> 啊 不好意思导致你封禁了，这个功能确实还有些问题，暂时别使用了

并不要紧，我在使用自动打牌的之前就考虑过这个问题了，应该是举报导致的。

**Comment by FlyingBamboo** [comment]
> > 别用自动打牌吧，或者优化一下再用。。没有吃碰，不防即立，能上分吗
> > 另外好像有坐庄的时候不能自动打牌的BUG，因为初始派牌的动画时间太长了
> 
> 是这样的，我另外写了个监控软件配合它想打一晚上收集一下牌谱，然后丢给借鉴AI的引擎，想看看在0副露的情况下，胜率是怎么样的，愚听和振听的情况未考虑这点我是知道的。然后懒得注册一个小号直接用大号上了，结果今天晚上7点就产生了封禁。

收集牌谱好想法啊

**Comment by Fr0stbyteR** [comment]
> > 别用自动打牌吧，或者优化一下再用。。没有吃碰，不防即立，能上分吗
> > 另外好像有坐庄的时候不能自动打牌的BUG，因为初始派牌的动画时间太长了
> 
> 是这样的，我另外写了个监控软件配合它想打一晚上收集一下牌谱，然后丢给借鉴AI的引擎，想看看在0副露的情况下，胜率是怎么样的，愚听和振听的情况未考虑这点我是知道的。然后懒得注册一个小号直接用大号上了，结果今天晚上7点就产生了封禁。

玉场金场都是有单独网址的观战广播的，用那个效率应该可以很高，同时收好几个。

**Comment by FlyingBamboo** [comment]
> > > 别用自动打牌吧，或者优化一下再用。。没有吃碰，不防即立，能上分吗
> > > 另外好像有坐庄的时候不能自动打牌的BUG，因为初始派牌的动画时间太长了
> > 
> > 
> > 是这样的，我另外写了个监控软件配合它想打一晚上收集一下牌谱，然后丢给借鉴AI的引擎，想看看在0副露的情况下，胜率是怎么样的，愚听和振听的情况未考虑这点我是知道的。然后懒得注册一个小号直接用大号上了，结果今天晚上7点就产生了封禁。
> 
> 玉场金场都是有单独网址的观战广播的，用那个效率应该可以很高，同时收好几个。

我一直在想收集牌谱的问题，这个绝赞。

**Comment by luciouskami** [comment]
> > > > 别用自动打牌吧，或者优化一下再用。。没有吃碰，不防即立，能上分吗
> > > > 另外好像有坐庄的时候不能自动打牌的BUG，因为初始派牌的动画时间太长了
> > > 
> > > 
> > > 是这样的，我另外写了个监控软件配合它想打一晚上收集一下牌谱，然后丢给借鉴AI的引擎，想看看在0副露的情况下，胜率是怎么样的，愚听和振听的情况未考虑这点我是知道的。然后懒得注册一个小号直接用大号上了，结果今天晚上7点就产生了封禁。
> > 
> > 
> > 玉场金场都是有单独网址的观战广播的，用那个效率应该可以很高，同时收好几个。
> 
> 我一直在想收集牌谱的问题，这个绝赞。

是的，不像围棋有空开的棋谱库，不知道天凤是不是公开了。

**Comment by iamapig120** [comment]
坐庄的时候不能自动打牌的BUG可以通过 raf 等方式等待到手牌为 14 张的时候再判断打什么牌，此外再加入 3s 左右的打牌延迟

**Comment by Fr0stbyteR** [comment]
> 0延迟导致封禁，7天（可能是因为我号比较值钱）

虽然没测试，但是已经随机延迟已经写好了
