### ISSUE TITLE
雀魂更新导致 ui.mj.desktopInfoUI.uiView 为空

### ISSUE THREAD

**Issue by iamapig120** [Fr0stbyteR/Majsoul-Helper#34]
可能需要别的方式来修改显示的 UI 替代当前玩法
现在段位显示等无法正常使用了

**Comment by DCxDESIGN** [comment]
跟牌河相关的功能全部都失效了，自动胡牌也不再能自动标记

**Comment by Fr0stbyteR** [comment]
> 可能需要别的方式来修改显示的 UI 替代当前玩法
> 现在段位显示等无法正常使用了
> 跟牌河相关的功能全部都失效了，自动胡牌也不再能自动标记

现在官方 Lazy load 了 UI 的布局，导致插件无法找到原来的注入点。
新的入口是`Laya.View.uiMap`，插件已经更新。
