### ISSUE TITLE
自动模式下另一个bug

### ISSUE THREAD

**Issue by christensennn** [Fr0stbyteR/Majsoul-Helper#36]
ai有时按照牌理走特殊番型 此时
到听牌/一向听的时候自动模式会失效。
![QQ拼音截图20190405165428](https://user-images.githubusercontent.com/42790204/55616046-88fc8300-57c3-11e9-9ac6-010b09289004.png)
如图听国士无双 此时自动模式失效 时间结束将1s打出
望修正 谢谢

**Comment by christensennn** [comment]
同时有出现：一局结束 确定键3秒后 卡在 等待其他玩家 页面 的情况

**Comment by christensennn** [comment]
还有一点就是 雀魂现在的ai会副露带役的字牌 字牌的利用率提高了很多 这边的话是否会考虑呢

**Comment by Fr0stbyteR** [comment]
> 还有一点就是 雀魂现在的ai会副露带役的字牌 字牌的利用率提高了很多 这边的话是否会考虑呢

不好意思，因为影响游戏平衡，并且会被官方封禁，所以 AI 麻将不在我的维护范围之内。
