### ISSUE TITLE
无法打开控制台

### ISSUE THREAD

**Issue by jerryzmtz** [Fr0stbyteR/Majsoul-Helper#37]
使用的是最新的稳定版mac端的雀魂plus。按F12也没有什么反应。请问如何打开控制台？

**Comment by Fr0stbyteR** [comment]
在 Electron 里打开控制台的方式不同，可能是 Cmd + Opt + I,
如果不是 请联系雀魂Plus 的作者

**Comment by jerryzmtz** [comment]
好的，我研究了一下应该是cmd+I，问题已经解决，O(∩_∩)O谢谢！
