### ISSUE TITLE
这次版本更新后无法使用了

### ISSUE THREAD

**Issue by jtc23** [Fr0stbyteR/Majsoul-Helper#38]
有没有人出现一样的问题啊

**Comment by Fr0stbyteR** [comment]
> 有没有人出现一样的问题啊

你好，是否更新到最新版本 0.4.5 了？

**Comment by jtc23** [comment]
> > 有没有人出现一样的问题啊
> 
> 你好，是否更新到最新版本 0.4.5 了？

哦哦原来是版本更新了吗。现在能正常使用了 感谢
