### ISSUE TITLE
雀魂更新后脚本无法使用

### ISSUE THREAD

**Issue by xurz97** [Fr0stbyteR/Majsoul-Helper#39]
当开脚本时，游戏加载不进去，卡在”正在整理牌桌“
去掉脚本可以正常游戏

**Comment by Fr0stbyteR** [comment]
> 当开脚本时，游戏加载不进去，卡在”正在整理牌桌“
> 去掉脚本可以正常游戏

修复好了 更新脚本到0.4.9之后应该就能正常使用了
