### ISSUE TITLE
好厉害qaq我想要用您写的脚本做个视频介绍投到B站

### ISSUE THREAD

**Issue by keyoujie12345** [Fr0stbyteR/Majsoul-Helper#4]
请问可以么qaq  我B站id是艾伦家养土赫萝

**Comment by keyoujie12345** [comment]
请求个授权qaq 不行的话也不强求来着_(:з」∠)_ 真的很方便省了我好多脑细胞

**Comment by Fr0stbyteR** [comment]
> 请求个授权qaq 不行的话也不强求来着_(:з」∠)_ 真的很方便省了我好多脑细胞

如果是自动打麻将的脚本可能会导致你被封禁，其他的话都没问题。我B站ID 弘子

**Comment by keyoujie12345** [comment]
噗 秒回！    我不用自动打麻将的qwq   因为自动的话没啥乐趣了   我也不是工作室啥的  用QQ聊么  1433985185

**Comment by keyoujie12345** [comment]
lv6的dalao！QAQ
