### ISSUE TITLE
如何关闭默认自动和牌？

### ISSUE THREAD

**Issue by celie1** [Fr0stbyteR/Majsoul-Helper#47]
非常感谢！

**Comment by Fr0stbyteR** [comment]
不好意思 默认自动和牌开关的功能并没有做

**Comment by celie1** [comment]
> 不好意思 默认自动和牌开关的功能并没有做

现在自动和了按钮默认开启，没有关闭的方法吗？

**Comment by Fr0stbyteR** [comment]
可以删除代码的第244行和第246行 分别是
`view.DesktopMgr.Inst.setAutoHule(true);`
`uiscript.UIMgr.Inst._ui_desktop.refreshFuncBtnShow(uiscript.UIMgr.Inst._ui_desktop._container_fun.getChildByName("btn_autohu"),` 1);

**Comment by celie1** [comment]
> 可以删除代码的第244行和第246行 分别是
> `view.DesktopMgr.Inst.setAutoHule(true);`
> `uiscript.UIMgr.Inst._ui_desktop.refreshFuncBtnShow(uiscript.UIMgr.Inst._ui_desktop._container_fun.getChildByName("btn_autohu"),` 1);

成功了，再次感谢作者快速的回复。
