### ISSUE TITLE
你好 如何关闭默认的自动胡

### ISSUE THREAD

**Issue by ShadySad** [Fr0stbyteR/Majsoul-Helper#50]

**Comment by Fr0stbyteR** [comment]
可以注释掉以下两行代码
https://github.com/Fr0stbyteR/Majsoul-Helper/blob/7293a87e9a34d5c486a8d0de55ba26fd9021fcc6/main.js#L244
https://github.com/Fr0stbyteR/Majsoul-Helper/blob/7293a87e9a34d5c486a8d0de55ba26fd9021fcc6/main.js#L246
